### ISSUE TITLE
add scripts to package.json

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/itsalmost-clone-server#2]
nodemon is installed as a dev dependency, make a script called `dev` that runs `index.js` with nodemon

**Comment by bryanurizar** [comment]
Can do this one too? But don't want to do too many and not allow others to pick up some of this stuff!

**Comment by BhavyaCodes** [comment]
Go ahead, there will be a lot of pull requests for this project

**Comment by bryanurizar** [comment]
Cool, should I also update the README.md with 'npm run dev'?
